name: Release

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install
        run: yarn
      - name: build
        run: yarn ci
      - run: |
          git config user.email "docsrncom@microsoft.com"
          git config user.name "Microsoft"
      - name: Beachball publish
        run: yarn run beachball:publish -y -n $NPM_FEED_PUBLISH_TOKEN
        env:
          NPM_FEED_PUBLISH_TOKEN: ${{ secrets.NPM_FEED_PUBLISH_TOKEN }}
